import type { HowToPlayEntry, NewsArticle } from "@/lib/tournaments/types";

export type SeniorMajorEvent = {
  slug: string;
  name: string;
  month: string; // e.g. "February 2026" or "Aug/Sep 2026"
  // Exact ISO dates for the event (preferred over `month` for resolvers).
  startDate?: string; // ISO "YYYY-MM-DD"
  endDate?: string; // ISO "YYYY-MM-DD"
  dates2026?: string; // optional precise human-readable label
  format?: string; // short label used on schedule + hubs (match Mid-Am style)
  note?: string;
  liveStatus?: "live" | "next" | "completed" | "upcoming";
  logo?: string;
  officialUrl?: string;
  golfGeniusUrl?: string;
  golfGeniusUrlLabel?: string;
  tournamentWebsite?: string;
  tournamentWebsiteLabel?: string;
  winners?: { year: number; champion: string }[];
  howToPlay?: HowToPlayEntry[];
  // Venue
  course?: string;
  location?: string;
  coursePar?: number;
  courseYardage?: number;
  courseDesigner?: string;
  // Format
  fieldSize?: string;
  eligibility?: string;
  // Editorial
  overview?: string;
  // History (richer than winners[])
  pastResults?: { year: number; champion: string; score?: string; runnerUp?: string; venue?: string }[];
  pastResultsVenueLabel?: string; // defaults to "Venue"; e.g. "Club" for four-ball/club-based events
  // News
  news?: NewsArticle[];
};

export const SENIOR_MAJOR_EVENTS_2026: SeniorMajorEvent[] = [
  {
    slug: "society-of-seniors-spring-classic",
    name: "Society of Seniors: Spring Classic",
    tournamentWebsite: "https://www.societyofseniors.com/",
    logo: "/brand/society-of-seniors.jpg",
    month: "February 2026",
    startDate: "2026-02-09",
    endDate: "2026-02-11",
    format: "54-hole stroke play",
    course: "Aileron Golf Club",
    location: "Lake Suzy, FL",
    coursePar: 72,
    courseYardage: 7235,
    courseDesigner: "Ron Garl (orig. 1976); redesigned Kipp Schulties (2023)",
    note: "Rotating venue; 2026 host: Aileron Golf Club, Lake Suzy, FL",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5666031",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Society of Seniors Spring Classic opens the SOS annual schedule and draws elite 55+ amateurs to rotating Florida venues each February. Founded in 1983, the Society of Seniors stages ten events annually across the country, and the Spring Classic has served as a premier season-opener for four-plus decades. The 2026 edition (18th) was hosted at the recently redesigned Aileron Golf Club in Lake Suzy.",
    pastResults: [
      { year: 2026, champion: "William Mallon", venue: "Aileron Golf Club" },
      { year: 2025, champion: "Doug Hanzel", venue: "World Golf Village (Slammer & Squire)" },
      { year: 2024, champion: "Rick Stimmel", venue: "Orange County National" },
      { year: 2023, champion: "Doug Clapp", venue: "Abacoa Golf Club" },
      { year: 2022, champion: "Bob Bailey", venue: "Hammock Beach Resort" },
      { year: 2021, champion: "Rusty Strawn", venue: "Orange County National" },
      { year: 2020, champion: "Ken Kinkopf", venue: "Abacoa Golf Club" },
      { year: 2019, champion: "Jim Lehman", venue: "Hammock Beach Golf Resort" },
      { year: 2018, champion: "Lewis Stephenson", venue: "Abacoa Golf Club" },
      { year: 2017, champion: "Keith Decker", venue: "Abacoa Golf Club" },
      { year: 2016, champion: "Keith Decker", venue: "Santa Lucia River Club" },
      { year: 2015, champion: "Michael Occi", venue: "Verandah Club" },
      { year: 2014, champion: "Stephen Sharpe", venue: "Bonita Bay Club East" },
      { year: 2013, champion: "Jim Lehman", venue: "Ironhorse GC" },
      { year: 2012, champion: "Mike Bodney", venue: "Twin Eagles GC" },
      { year: 2011, champion: "Duke Delcher", venue: "PGA Village" },
      { year: 2010, champion: "Chip Lutz", venue: "Santa Lucia River Club" },
      { year: 2009, champion: "Ron Carter", venue: "Pensacola CC" },
    ],
    howToPlay: [{ label: "Apply for invite", href: "https://www.societyofseniors.com/membership/" }],
  },
  {
    slug: "gasparilla-invitational-senior-division",
    name: "Gasparilla Invitational (Senior Division)",
    logo: "/brand/gasparilla.png",
    month: "February 2026",
    startDate: "2026-02-19",
    endDate: "2026-02-21",
    format: "54-hole stroke play",
    course: "Palma Ceia Golf & Country Club",
    location: "Tampa, FL",
    coursePar: 70,
    courseYardage: 6211,
    courseDesigner: "Donald Ross (redesign 1923)",
    tournamentWebsite: "https://gasparillainvitational.com/",
    golfGeniusUrl: "https://pcgc-71stgasparillainvitational.golfgenius.com/pages/11889495109525324281",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Gasparilla Invitational has been played at historic Palma Ceia Golf & Country Club in Tampa since the 1930s, making it one of Florida's oldest and most storied amateur events. Donald Ross's compact par-70 demands precision over power, with tight tree-lined fairways and small undulating greens. The senior division attracts the country's finest 55+ amateurs each February.",
    winners: [
      { year: 2026, champion: "Jeff Frazier" },
      { year: 2025, champion: "Miles McConnell" },
      { year: 2024, champion: "Miles McConnell" },
      { year: 2023, champion: "Rusty Strawn" },
      { year: 2022, champion: "Bob Royak" },
      { year: 2021, champion: "Jack Hall" },
      { year: 2020, champion: "Jimmy Jones" },
    ],
    howToPlay: [{ label: "Apply for invite here", href: "https://gasparillainvitational.com/" }],
  },
  {
    slug: "jones-cup-senior-invitational",
    name: "Jones Cup Senior Invitational",
    month: "February 2026",
    startDate: "2026-02-23",
    endDate: "2026-02-25",
    format: "54-hole stroke play",
    course: "Sea Island Golf Club (Seaside Course)",
    location: "St. Simons Island, GA",
    coursePar: 70,
    courseYardage: 6945,
    courseDesigner: "Harry Colt & Charles Alison (1929); Tom Fazio renovation (1999)",
    tournamentWebsite: "https://www.jonescupinvitational.com/senior-invitational/",
    golfGeniusUrl: "https://2026jonescupseniorinvitational.golfgenius.com/pages/12184924252813678440",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Jones Cup Senior Invitational is played on the iconic Seaside Course at Sea Island Golf Club \u2014 a storied coastal Georgia layout that melds original Colt-Alison architecture with a Fazio renovation. Part of the prestigious Jones Cup family, the senior event attracts elite 55+ amateurs to one of America\u2019s most celebrated golf destinations each February.",
    winners: [
      { year: 2026, champion: "Mike McCoy" },
      { year: 2025, champion: "Jeff Knox" },
      { year: 2024, champion: "Jack Larkin" },
      { year: 2023, champion: "Bob Royak" },
      { year: 2022, champion: "Matthew Sughrue" },
      { year: 2021, champion: "Doug Hanzel" },
      { year: 2020, champion: "Bob Royak" },
      { year: 2019, champion: "Doug Hanzel" },
      { year: 2018, champion: "Gene Elliott" },
      { year: 2017, champion: "Walter Todd" },
      { year: 2016, champion: "Mark Weston" },
      { year: 2015, champion: "Jack Hall" },
      { year: 2014, champion: "Doug Hanzel" },
      { year: 2013, champion: "Mike Bodney" },
      { year: 2012, champion: "Doug Hanzel" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "society-of-seniors-ed-tutwiler-four-ball",
    name: "Society of Seniors: Ed Tutwiler Four-Ball",
    tournamentWebsite: "https://www.societyofseniors.com/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5698461",
    golfGeniusUrlLabel: "2026 Results",
    logo: "/brand/society-of-seniors.jpg",
    month: "March 2026",
    startDate: "2026-03-15",
    endDate: "2026-03-18",
    course: "The Reserve Golf Club",
    location: "Pawleys Island, SC",
    pastResults: [
      { year: 2026, champion: "Fox & Channell", venue: "The Reserve Golf Club" },
      { year: 2025, champion: "Allen & Donatoni", venue: "The Reserve Golf Club" },
      { year: 2024, champion: "Semple & Durr", venue: "Cape Club of Palm City" },
      { year: 2023, champion: "Russo & Kennedy", venue: "Estero Country Club" },
      { year: 2022, champion: "Johnson & Bouguennec", venue: "Southern Pines GC" },
      { year: 2018, champion: "Mercier & Kircher", venue: "Kiva Dunes GC" },
      { year: 2017, champion: "Hudson & Field", venue: "Grayhawk GC - Raptor Course" },
      { year: 2016, champion: "Beck & Phillips", venue: "Spring Creek" },
      { year: 2015, champion: "Tallent & Irey", venue: "Fox Club" },
      { year: 2014, champion: "Johnson & Empanger", venue: "Hawks Nest GC" },
      { year: 2013, champion: "Smith & Fadel", venue: "Lake Jovita Golf & CC" },
      { year: 2012, champion: "Smith & Fadel", venue: "Ironhorse CC" },
      { year: 2011, champion: "Lefferdink & Earsley", venue: "The Wanderers Club" },
      { year: 2010, champion: "Price & Long", venue: "Pensacola CC" },
      { year: 2009, champion: "Greenbaum & Foster", venue: "Desert Mountain GC" },
      { year: 2008, champion: "Bauch & Miller", venue: "Spring Creek GC" },
      { year: 2007, champion: "Kulp & Simson", venue: "Forest Creek GC" },
      { year: 2006, champion: "Hart & Woulfe", venue: "Daniel Island Club" },
      { year: 2005, champion: "Brown & Maletis", venue: "Flint Hill National" },
      { year: 2004, champion: "Forbes & Persinger", venue: "Bulls Bay GC" },
      { year: 2003, champion: "Ploeger & Rice", venue: "Turtle Pint GC" },
      { year: 2002, champion: "Foster & Greenbaum", venue: "The Homestead-Cascades" },
      { year: 2001, champion: "Hullendur & Rice", venue: "Rancho Laquinta" },
      { year: 2000, champion: "Jacobi & Flory", venue: "Colo Vista CC" },
      { year: 1999, champion: "Jacobi & Flory", venue: "Forest Creek/Foxfire East" },
      { year: 1998, champion: "Bonney & Greenbaum", venue: "Orchid Island/Windsor Club" },
      { year: 1997, champion: "Jackson & Vardaman", venue: "Kiawah Island Club" },
      { year: 1996, champion: "Kemp & Stahl", venue: "Orchid Island/Windsor Club" },
      { year: 1995, champion: "Moyers & Sucher", venue: "Reynolds Plantation" },
      { year: 1994, champion: "Jones & Veghte", venue: "Reynolds Plantation" },
      { year: 1993, champion: "Estey & Ribelin", venue: "The Farm" },
      { year: 1992, champion: "Jones & Veghte", venue: "Landfall Club" },
      { year: 1991, champion: "Jones & Veghte", venue: "Landfall Club/ Haig Point" },
      { year: 1990, champion: "Simpson & Van Linge", venue: "Lake Nona GC" },
      { year: 1989, champion: "Cassel & Perderson", venue: "Lake Nona GC" },
      { year: 1988, champion: "Faison & Lowry", venue: "Loxahatchee Club" },
      { year: 1987, champion: "Harrison & Key", venue: "Loxahatchee Club" },
      { year: 1986, champion: "Morey & Rawlins", venue: "Lochinvar GC" },
      { year: 1985, champion: "Compton & Tutwiler", venue: "Lochinvar GC" },
      { year: 1984, champion: "Campbell & Derrick", venue: "Atlantic City CC" },
      { year: 1983, champion: "Brennan & Owens", venue: "Atlantic City CC" },
    ],
    howToPlay: [{ label: "Apply for invite", href: "https://www.societyofseniors.com/membership/" }],
  },
  {
    slug: "golfweek-senior-amateur-championship",
    name: "Golfweek Senior Amateur Championship",
    logo: "/brand/GwkSrNation_BADGE.svg",
    month: "March/April 2026",
    startDate: "2026-03-30",
    endDate: "2026-04-02",
    format: "54-hole stroke play",
    course: "Desert Willow Golf Resort (The Firecliff Course)",
    location: "Palm Desert, CA",
    tournamentWebsite: "https://golfweekseniornation.com/",
    golfGeniusUrl: "https://www.golfgenius.com/leagues/12156704060203865310/rounds/12156704220828931295/v2tournaments",
    golfGeniusUrlLabel: "2026 Results",
    note: "Rotating venue; 2026 host: Desert Willow Golf Resort (The Firecliff Course), Palm Desert, CA",
    overview: "The Golfweek Senior Amateur Championship is an elite invitation-only stroke-play event on the national senior amateur calendar, contested over 54 holes at a top-ranked venue each year. It sets itself apart from most senior invitationals with a deep national field and a rotating slate of premier courses.",
    pastResults: [
      { year: 2026, champion: "Todd Doss", venue: "Desert Willow Golf Resort (Firecliff)" },
      { year: 2025, champion: "Bryan Hoops", venue: "Desert Willow Golf Resort (Firecliff)" },
      { year: 2024, champion: "Mark Strickland", venue: "Desert Willow Golf Resort (Firecliff)" },
      { year: 2023, champion: "Vance Welch", venue: "Desert Willow Golf Resort (Firecliff)" },
      { year: 2022, champion: "Robert Funk", venue: "PGA West (Pete Dye Dunes)" },
      { year: 2021, champion: "Craig Davis", venue: "PGA West (Pete Dye Dunes)" },
      { year: 2020, champion: "Jack Larkin", venue: "Mission Hills Country Club" },
      { year: 2019, champion: "Gregory Condon", venue: "Mission Hills Country Club" },
      { year: 2018, champion: "Gene Elliott", venue: "Desert Willow Golf Resort" },
      { year: 2017, champion: "Mitch Wilson", venue: "Desert Willow Golf Resort" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "george-coleman-invitational-senior-division",
    name: "George Coleman Invitational (Senior Division)",
    month: "April 2026",
    startDate: "2026-04-13",
    endDate: "2026-04-15",
    format: "54-hole stroke play",
    course: "Seminole Golf Club",
    location: "Juno Beach, FL",
    coursePar: 72,
    courseYardage: 7265,
    courseDesigner: "Donald Ross (1929)",
    note: "Seminole Golf Club undergoing fairway renovations to address a rising water table; venue for 2026 pending confirmation",
    overview: "The George L. Coleman Senior Invitational is held at Seminole Golf Club \u2014 Donald Ross\u2019s celebrated oceanside masterpiece and one of the world\u2019s most coveted private courses. The senior division places the nation\u2019s best 55+ amateurs on Seminole\u2019s wind-swept, links-influenced layout, and the event is widely regarded as the pinnacle of the senior amateur invitational circuit.",
    winners: [
      { year: 2024, champion: "Mike McCoy" },
      { year: 2023, champion: "Roger Newsom" },
      { year: 2022, champion: "Bob Royak" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "society-of-seniors-senior-masters",
    name: "Society of Seniors: Senior Masters",
    tournamentWebsite: "https://www.societyofseniors.com/",
    logo: "/brand/society-of-seniors.jpg",
    month: "April 2026",
    startDate: "2026-04-20",
    endDate: "2026-04-22",
    format: "54-hole stroke play",
    course: "Indian Wells Golf Resort (Players & Celebrity Courses)",
    location: "Indian Wells, CA",
    courseDesigner: "John Fought (Players, 2007); Clark (Celebrity)",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5722470",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Society of Seniors Senior Masters is held each April at the prestigious Indian Wells Golf Resort in California\u2019s Coachella Valley. Competitors play on both the Fought-designed Players Course and the Clark-designed Celebrity Course across four age divisions \u2014 Senior, Super Senior, Legend, and Super Legend \u2014 all contested in 54-hole stroke play.",
    winners: [
      { year: 2026, champion: "Bryan Hoops" },
      { year: 2025, champion: "Bryan Hoops" },
      { year: 2024, champion: "Randy Haag" },
      { year: 2023, champion: "Lee Porter" },
      { year: 2022, champion: "Jerry Rose" },
      { year: 2021, champion: "John Derrick" },
      { year: 2020, champion: "Cancelled (pandemic)" },
      { year: 2019, champion: "Ken Kinkopf" },
      { year: 2018, champion: "Peter DeTemple" },
      { year: 2017, champion: "Steve Hudson" },
      { year: 2016, champion: "Steve Hudson" },
      { year: 2015, champion: "Doug Pool" },
      { year: 2014, champion: "Steve Hudson" },
      { year: 2013, champion: "Jeff Burda" },
      { year: 2012, champion: "Tom Hyland" },
    ],
    howToPlay: [{ label: "Apply for invite", href: "https://www.societyofseniors.com/membership/" }],
  },
  {
    slug: "trans-mississippi-senior-championship",
    name: "Trans-Mississippi Senior Championship",
    month: "May 2026",
    startDate: "2026-05-04",
    endDate: "2026-05-06",
    format: "54-hole stroke play",
    course: "Mission Hills Country Club",
    location: "Rancho Mirage, CA",
    note: "Rotating venue; 2026 host: Mission Hills Country Club, Rancho Mirage, CA",
    tournamentWebsite: "https://trans-miss.org/tournaments/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12345135326027593444",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Trans-Mississippi Senior Championship, organized by the Trans-Mississippi Golf Association since 2000, is one of America\u2019s most prestigious regional senior titles. The event rotates annually among distinguished courses west of the Mississippi River, drawing elite 55+ amateurs for 54 holes of stroke play each May.",
    pastResults: [
      { year: 2026, champion: "Jason Pridmore", venue: "Mission Hills Country Club, Rancho Mirage, CA" },
      { year: 2025, champion: "Bryan Hoops", venue: "Thunderbird Country Club, Rancho Mirage, CA" },
      { year: 2024, champion: "Terrence Miskell", venue: "Blessings Golf Club, Fayetteville, AR" },
      { year: 2023, champion: "Jon Lindstrom", venue: "Hacienda Golf Club, La Habra Heights, CA" },
      { year: 2022, champion: "Rusty Strawn", venue: "Trinity Forest Golf Club, Dallas, TX" },
      { year: 2021, champion: "Steve Maddalena", venue: "Meadow Club, Fairfax, CA" },
      { year: 2020, champion: "Cancelled (COVID-19)", venue: "Hacienda Golf Club, La Habra Heights, CA" },
      { year: 2019, champion: "Lewis Stephenson", venue: "La Quinta Country Club, La Quinta, CA" },
      { year: 2018, champion: "Mike McCoy", venue: "Desert Forest Golf Club, Carefree, AZ" },
      { year: 2017, champion: "Gene Elliott", venue: "Eldorado Country Club, Indian Wells, CA" },
      { year: 2016, champion: "Tommy Brennan", venue: "Houston Country Club, Houston, TX" },
      { year: 2015, champion: "Jeff New", venue: "Brook Hollow Golf Club, Dallas, TX" },
      { year: 2014, champion: "Jeff Burda", venue: "La Quinta Country Club, La Quinta, CA" },
      { year: 2013, champion: "Corky Nelson", venue: "The Gallery Golf Club, Tucson, AZ" },
      { year: 2012, champion: "Pat Duncan, Sr.", venue: "La Jolla Country Club, La Jolla, CA" },
      { year: 2011, champion: "Chris Maletis", venue: "Brook Hollow Golf Club, Dallas, TX" },
      { year: 2010, champion: "Chip Lutz", venue: "Denver Country Club, Denver, CO" },
      { year: 2009, champion: "Jerry Greenbaum", venue: "Flint Hills National Golf Club, Andover, KS" },
      { year: 2008, champion: "Roger Brown", venue: "Wakonda Club, Des Moines, IA" },
      { year: 2007, champion: "Chris Maletis", venue: "The Minikahda Club, Minneapolis, MN" },
      { year: 2006, champion: "Steven Hakes", venue: "Brook Hollow Golf Club, Dallas, TX" },
      { year: 2005, champion: "Chris Maletis", venue: "Prairie Dunes Country Club, Hutchinson, KS" },
      { year: 2004, champion: "Chris Maletis", venue: "La Jolla Country Club, La Jolla, CA" },
      { year: 2003, champion: "Nick Onofrio", venue: "Flint Hills National Golf Club, Andover, KS" },
      { year: 2002, champion: "Billy Clagett", venue: "Barton Creek Golf Club, Austin, TX" },
      { year: 2001, champion: "Billy Clagett", venue: "Kansas City Country Club, Mission Hills, KS" },
      { year: 2000, champion: "Jerry Gruidl", venue: "White Bear Yacht Club, White Bear Lake, MN" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "john-t-lupton-memorial-senior-division",
    name: "John T. Lupton Memorial (Senior Division)",
    logo: "/brand/Lupton.jpeg",
    month: "May 2026",
    startDate: "2026-05-11",
    endDate: "2026-05-13",
    format: "54-hole stroke play",
    course: "The Honors Course",
    location: "Ooltewah, TN",
    coursePar: 72,
    courseYardage: 6915,
    courseDesigner: "Pete Dye (1983)",
    overview: "The John T. Lupton Memorial is played at The Honors Course in Ooltewah, Tennessee \u2014 Pete Dye\u2019s tribute to amateur golf, commissioned by Coca-Cola heir Jack Lupton. The senior division (55+) earns World Amateur Golf Ranking points alongside the concurrent mid-amateur division. Consistently ranked among the nation\u2019s top-100 private courses, the Honors Course is one of Dye\u2019s finest designs.",
    winners: [
      { year: 2025, champion: "Jack Larkin" },
      { year: 2024, champion: "Mike Combs" },
      { year: 2023, champion: "Bob Royak" },
      { year: 2018, champion: "Rick Cloninger" },
      { year: 2014, champion: "Paul Simson" },
      { year: 2013, champion: "Paul Simson" },
      { year: 2012, champion: "Doug Hanzel" },
      { year: 2011, champion: "Brady Exber" },
      { year: 2010, champion: "Chip Lutz" },
      { year: 2009, champion: "Paul Simson" },
      { year: 2008, champion: "Paul Simson" },
      { year: 2007, champion: "Paul Simson" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "huddleston-cup-senior-division",
    name: "The Huddleston Cup (Senior Division)",
    logo: "/brand/Huddleston.png",
    month: "May 2026",
    liveStatus: "completed",
    startDate: "2026-05-26",
    endDate: "2026-05-28",
    format: "54-hole stroke play",
    course: "Maridoe Golf Club",
    location: "Carrollton, TX",
    coursePar: 72,
    courseYardage: 7834,
    courseDesigner: "Steve Smyers (2017)",
    tournamentWebsite: "https://www.golfgenius.com/pages/12245787646592317936",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12245787651055057396",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Huddleston Cup at Maridoe Golf Club in Carrollton, Texas is one of the most demanding tests in senior amateur golf. Maridoe\u2019s par-72 layout stretches to 7,834 yards with a 155 slope rating \u2014 the maximum possible \u2014 and the inaugural 2023 event has quickly become one of the circuit\u2019s most coveted invitationals for elite 55+ amateurs.",
    winners: [
      { year: 2026, champion: "Bob Royak" },
      { year: 2025, champion: "Bryan Hoops" },
      { year: 2023, champion: "Doug Hanzel" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "anderson-memorial-four-ball-senior-division",
    name: "Anderson Memorial Four-Ball (Senior Division)",
    logo: "/brand/Anderson Memorial.jpeg",
    month: "June 2026",
    liveStatus: "completed",
    startDate: "2026-06-03",
    endDate: "2026-06-07",
    dates2026: "June 3-7, 2026",
    format: "Match play (four-ball, two-man teams)",
    course: "Winged Foot Golf Club",
    location: "Mamaroneck, NY",
    coursePar: 72,
    courseYardage: 7426,
    courseDesigner: "A.W. Tillinghast",
    overview: "The senior division of the Anderson Memorial Four-Ball gathers 55-and-over amateurs for two-man better-ball match play at Winged Foot Golf Club in Mamaroneck, New York. The 2026 event runs June 3-7.",
    tournamentWebsite: "https://andersonmemorial.org/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12365089316366476022",
    golfGeniusUrlLabel: "2026 Results",
    pastResultsVenueLabel: "Club",
    howToPlay: [{ label: "Invite only — submit application", href: "https://andersonmemorial.org/" }],
    pastResults: [
      { year: 2026, champion: "Eoghan O'Connell / Seth Sargent", venue: "Pine Valley Golf Club" },
      { year: 2025, champion: "Mike Peck / Bart Goodwin", venue: "Golf Clubs of the Tribute" },
      { year: 2024, champion: "Dave Staudinger / Matthew Meyer", venue: "Winged Foot GC" },
      { year: 2023, champion: "Jack Larkin / Mike Brown", venue: "Peachtree Golf Club, GA" },
      { year: 2022, champion: "Dave Scialabba / Patrick Tallent", venue: "Indian Creek Country Club" },
      { year: 2021, champion: "Christopher Lange / Chip Lutz", venue: "Pine Valley Golf Club" },
      { year: 2020, champion: "No tournament" },
      { year: 2019, champion: "Matt Sughrue / John Lombardozzi", venue: "Trump National Golf Club" },
      { year: 2018, champion: "Allen Strange / Dean Channell", venue: "Country Club of North Carolina" },
      { year: 2017, champion: "Mike Peck / Bart Goodwin", venue: "Old American Golf Club" },
      { year: 2016, champion: "George Zahringer / Brady Exber", venue: "The Floridian" },
      { year: 2015, champion: "John Benson / Don Erickson", venue: "Punxsutawney Country Club" },
      { year: 2014, champion: "Bart Goodwin / Mike Peck", venue: "Old American Golf Club" },
      { year: 2013, champion: "Bart Goodwin / Mike Peck", venue: "Old American Golf Club" },
      { year: 2012, champion: "Jim Holtgrieve / Tom Case", venue: "Pine Valley Golf Club" },
      { year: 2011, champion: "Chris Lange / Chris Lutz", venue: "Pine Valley Golf Club" },
      { year: 2010, champion: "John Benson / Don Erickson III", venue: "Punxsutawney County Club" },
      { year: 2009, champion: "Jerry Greenbaum / Mark Rubin", venue: "Adios Golf Club" },
      { year: 2008, champion: "Jody Vasquez / John Granger", venue: "Colonial Country Club" },
      { year: 2007, champion: "Ned Steiner / Dick Lockwood", venue: "Red Tail Golf Club" },
      { year: 2006, champion: "David Brookreson / Craig Scott", venue: "Huntingdon Valley Country Club" },
      { year: 2005, champion: "Bob Hullender / Mike Rice", venue: "Tapatio Springs Golf Club" },
      { year: 2004, champion: "Bob Hullender / Mike Rice", venue: "Tapatio Springs Golf Club" },
      { year: 2003, champion: "Bob Hullender / Mike Rice", venue: "Desert Mountain" },
      { year: 2002, champion: "John Mckey / Jack Vardaman", venue: "Pine Valley Golf Club" },
      { year: 2001, champion: "John Mckey / Jack Vardaman", venue: "Pine Valley Golf Club" },
      { year: 2000, champion: "John Mckey / Jack Vardaman", venue: "Pine Valley Golf Club" },
      { year: 1999, champion: "Bob Hullender / Mike Rice", venue: "Tapatio Springs Golf Club" },
      { year: 1998, champion: "James W Fitzgerald / Donald W. Edwards", venue: "Winged Foot Golf Club" },
      { year: 1997, champion: "Jim Mcmurtrey / Bob Olds", venue: "Brentwood Country Club" },
      { year: 1996, champion: "Bob Hullender / Mike Rice", venue: "Tapatio Spring Golf Club" },
    ],
  },
  {
    slug: "cb-macdonald-invitational-senior-division",
    name: "C.B. Macdonald Invitational (Senior Division)",
    logo: "/brand/CB Macdonald.jpeg",
    month: "June 2026",
    liveStatus: "completed",
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    dates2026: "June 12-14, 2026",
    format: "Match play",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12787897523763194722",
    course: "National Golf Links of America",
    location: "Southampton, NY",
    coursePar: 73,
    courseYardage: 6779,
    courseDesigner: "Charles B. Macdonald",
    overview: "The C.B. Macdonald Invitational Senior Division is contested over the storied National Golf Links of America in Southampton, New York, host of the first Walker Cup in 1922. Played at the same venue and on the same June dates as the mid-amateur championship, the senior division gathers elite 55-and-over amateurs for match play across one of the most revered courses in American golf. Its par-73 routing along Peconic Bay rewards imagination and shotmaking over raw power.",
    winners: [{ year: 2026, champion: "Dan Keogh" }],
    howToPlay: [{ label: "Invite only — no application" }],
  },
  {
    slug: "ra-senior-amateur",
    name: "R&A Senior Amateur Championship",
    logo: "/brand/randalogo.svg",
    month: "July 2026",
    startDate: "2026-07-07",
    endDate: "2026-07-10",
    dates2026: "July 7\u201310, 2026",
    liveStatus: "completed",
    format: "stroke play",
    course: "Frilford Heath Golf Club",
    location: "Abingdon, Oxfordshire, England",
    note: "Rotating venue; 2026 host: Frilford Heath Golf Club, Abingdon, Oxfordshire",
    tournamentWebsite: "https://www.randa.org/championships/the-senior-amateur-championship",
    golfGeniusUrl: "https://www.randa.org/championships/senior-amateur-leaderboard",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The R&A Senior Amateur Championship is the world\u2019s premier international senior amateur title, staged annually at rotating links and heathland courses across Great Britain and Ireland. Players 55 and over compete in stroke play, and the champion is widely regarded as the top senior amateur in the world.",
    pastResults: [
      { year: 2026, champion: "Bryan Hoops", venue: "Frilford Heath Golf Club" },
      { year: 2025, champion: "John Kennedy", venue: "Walton Heath", score: "277" },
      { year: 2024, champion: "Todd White", venue: "Saunton", score: "291" },
      { year: 2023, champion: "Brent Paterson", venue: "Woodhall Spa", score: "283" },
      { year: 2022, champion: "Mike McCoy", venue: "Royal Dornoch", score: "283" },
      { year: 2021, champion: "Gene Elliot", venue: "Ganton", score: "290" },
      { year: 2020, champion: "No championship (COVID-19)" },
      { year: 2019, champion: "Craig Davis", venue: "North Berwick", score: "207" },
      { year: 2018, champion: "Trevor Foster", venue: "Royal Porthcawl", score: "208" },
      { year: 2017, champion: "Bryan Hughes", venue: "Sunningdale (Old Course)", score: "214" },
      { year: 2016, champion: "Chip Lutz", venue: "Formby", score: "220" },
      { year: 2015, champion: "Patrick Tallent", venue: "Royal County Down", score: "218" },
      { year: 2014, champion: "Brady Exber", venue: "Ganton", score: "224" },
      { year: 2013, champion: "George Zahringer", venue: "Royal Aberdeen", score: "218" },
      { year: 2012, champion: "Chip Lutz", venue: "Machynys Peninsula", score: "211" },
      { year: 2011, champion: "Chip Lutz", venue: "Royal Portrush", score: "214" },
      { year: 2010, champion: "Paul Simson", venue: "Walton Heath", score: "208" },
      { year: 2009, champion: "Robert Vallis", venue: "Prestwick", score: "224" },
      { year: 2008, champion: "Paul Simson", venue: "Royal Cinque Ports/Prince's", score: "216" },
      { year: 2007, champion: "Arthur Pierse", venue: "Nairn/Nairn Dunbar", score: "211" },
      { year: 2006, champion: "Paul Simson", venue: "Saunton (East & West)", score: "223" },
      { year: 2005, champion: "Alan Foster", venue: "Woburn (Duke's & Duchess)", score: "222" },
      { year: 2004, champion: "Kemp Richardson", venue: "The Berkshire (Red & Blue)", score: "213" },
      { year: 2003, champion: "Roy Smethurst", venue: "Blairgowrie (Rosemount & Landsdowne)", score: "215" },
      { year: 2002, champion: "John Baldwin", venue: "Woodhall Spa (Hotchkin & Bracken)", score: "216" },
      { year: 2001, champion: "Kemp Richardson", venue: "Royal Portrush (Dunluce & Valley)", score: "217" },
      { year: 2000, champion: "Joel Hirsch", venue: "Gullane (No.1 & No.2)", score: "218" },
      { year: 1999, champion: "William Shean Jr", venue: "Frilford Heath (Red & Blue)", score: "219" },
      { year: 1998, champion: "David Lane", venue: "Western Gailes/Glasgow Gailes", score: "221" },
      { year: 1997, champion: "Bud Bradley", venue: "Sherwood Forest/Coxmoor", score: "216" },
      { year: 1996, champion: "Joel Hirsch", venue: "Blairgowrie (Rosemount & Lansdowne)", score: "210" },
      { year: 1995, champion: "Graham Steel", venue: "Hankley Common/Farnham", score: "218" },
      { year: 1994, champion: "Charles W Green", venue: "Formby/Southport & Ainsdale", score: "223" },
      { year: 1993, champion: "Charles W Green", venue: "Royal Aberdeen/Murcar", score: "150" },
      { year: 1992, champion: "Clifford Hartland", venue: "Ipswich Purdis Heath/Woodbridge", score: "221" },
      { year: 1991, champion: "Charles W Green", venue: "Prestwick/Prestwick St Nicholas", score: "219" },
      { year: 1990, champion: "Charles W Green", venue: "The Berkshire", score: "207" },
      { year: 1989, champion: "Charles W Green", venue: "Moortown/Alwoodley", score: "226" },
      { year: 1988, champion: "Charles W Green", venue: "Royal Burgess/Bruntsfield", score: "221" },
      { year: 1987, champion: "Bill Soyars", venue: "Royal Cinque Ports/Prince's", score: "226" },
      { year: 1986, champion: "Noel Sturrock", venue: "Panmure/Carnoustie", score: "229" },
      { year: 1985, champion: "Dale Morey", venue: "Hesketh/Southport & Ainsdale", score: "223" },
      { year: 1984, champion: "John Owens", venue: "Western Gailes/Glasgow Gailes", score: "222" },
      { year: 1983, champion: "A J Swann", venue: "Walton Heath", score: "222" },
      { year: 1982, champion: "R L Glading", venue: "Blairgowrie", score: "218" },
      { year: 1981, champion: "T Branton", venue: "Royal Liverpool", score: "227" },
      { year: 1980, champion: "J M Cannon", venue: "Prestwick St Nicholas", score: "218" },
      { year: 1979, champion: "R J White", venue: "Royal St David's", score: "226" },
      { year: 1978, champion: "R J White", venue: "Formby", score: "225" },
      { year: 1977, champion: "Dr T E Donaldson", venue: "Panmure", score: "228" },
      { year: 1976, champion: "W M Crichton", venue: "Berkshire", score: "149" },
      { year: 1975, champion: "H J Roberts", venue: "Turnberry", score: "138" },
      { year: 1974, champion: "M A Ivor-Jones", venue: "Moortown", score: "149" },
      { year: 1973, champion: "J T Jones", venue: "Royal Liverpool", score: "142" },
      { year: 1972, champion: "T C Hartley", venue: "St Andrews", score: "147" },
      { year: 1971, champion: "G H Pickard", venue: "Royal Cinque Ports/Royal St George's", score: "150" },
      { year: 1970, champion: "K Bamber", venue: "Prestwick", score: "150" },
      { year: 1969, champion: "R Pattinson", venue: "Formby", score: "154" },
    ],
    howToPlay: [
      {
        label: "Open entry via randa.org",
        href: "https://www.randa.org/championship-entries",
        note: "Age 55+, Handicap Index of 2.4 or better; exempt categories (past champions, Amateur/Mid-Am/Senior Open players, Walker Cup alumni, etc.) fill first, remaining spots by lowest handicap",
      },
    ],
  },
  {
    slug: "sunnehanna-senior-amateur",
    name: "Sunnehanna Senior Amateur Championship",
    logo: "/brand/sunnehanna-senior-amateur.svg",
    month: "August 2026",
    dates2026: "August 16-19, 2026",
    startDate: "2026-08-16",
    endDate: "2026-08-19",
    liveStatus: "completed",
    format: "54-hole stroke play",
    course: "Sunnehanna Country Club",
    location: "Johnstown, PA",
    coursePar: 70,
    courseYardage: 6716,
    courseDesigner: "A.W. Tillinghast (1923)",
    tournamentWebsite: "https://www.sunnehanna.org/senior/tournament-info",
    golfGeniusUrl: "https://www.sunnehanna.org/senior/results",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Sunnehanna Senior Amateur Championship is played at historic Sunnehanna Country Club in Johnstown, Pennsylvania \u2014 an A.W. Tillinghast design that also hosts the renowned Sunnehanna Amateur. The course has attracted amateur golf legends since 1923, and the senior championship gives elite 55+ amateurs the chance to compete on one of Pennsylvania\u2019s finest classic layouts.",
    winners: [
      { year: 2026, champion: "Miles McConnell" },
      { year: 2025, champion: "Tony Wise" },
      { year: 2024, champion: "Mark Strickland" },
      { year: 2023, champion: "Sean Knapp" },
      { year: 2021, champion: "Kevin Vandenberg" },
      { year: 2020, champion: "Sherrill Britt" },
      { year: 2019, champion: "John Derrick" },
      { year: 2017, champion: "Sean Knapp" },
      { year: 2016, champion: "Bob Kearney" },
      { year: 2015, champion: "Don Erickson" },
      { year: 2014, champion: "Dave Lucks" },
      { year: 2013, champion: "Sam Lewis" },
      { year: 2012, champion: "Don Erickson" },
      { year: 2010, champion: "Chip Lutz" },
      { year: 2009, champion: "Bob Allshouse" },
      { year: 2008, champion: "John Baldwin" },
      { year: 2007, champion: "Mike Rice" },
      { year: 2006, champion: "Ronnie Tumlin" },
      { year: 2005, champion: "Bob Hullender" },
    ],
    howToPlay: [
      {
        label: "Enter here",
        href: "https://www.sunnehanna.org/senior/tournament-info",
        note: "Exempt players who enter before the deadline are accepted automatically; all other entries are treated as an indication of interest and accepted at the Committee's discretion, not by entry order",
      },
    ],
  },
  {
    slug: "north-south-senior-mens-amateur",
    name: "North & South Senior Men's Amateur Championship",
    logo: "/brand/north-south-senior-amateur.png",
    month: "August 2026",
    startDate: "2026-08-10",
    endDate: "2026-08-12",
    dates2026: "August 10-12, 2026",
    liveStatus: "completed",
    format: "54-hole stroke play",
    course: "Pinehurst Resort (Nos. 4, 5 & 8)",
    location: "Pinehurst, NC",
    courseDesigner: "Various",
    tournamentWebsite: "https://www.pinehurst.com/golf/tournaments/north-south-senior-amateur/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/6117762",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The North & South Senior Men's Amateur Championship is contested over 54 holes of stroke play at Pinehurst Resort, with one round apiece on Nos. 4, 5, and 8. Split into Open and Super-Senior divisions, it is one of the oldest and most celebrated senior amateur championships in the country, drawing a national field of elite amateurs to the Sandhills of North Carolina each August.",
    winners: [
      { year: 2026, champion: "Rick Stewart" },
      { year: 2025, champion: "Howard Clendenin" },
      { year: 2024, champion: "Stan Humphries" },
      { year: 2023, champion: "Bob Royak" },
      { year: 2022, champion: "Sherrill Britt" },
      { year: 2021, champion: "Todd Hendley" },
      { year: 2020, champion: "Paul Simson" },
      { year: 2019, champion: "Ken Kinkopf" },
      { year: 2018, champion: "Eddie Hargett" },
      { year: 2017, champion: "Todd Hendley" },
      { year: 2016, champion: "Paul Simson" },
      { year: 2015, champion: "Paul Simson" },
      { year: 2014, champion: "George Walker" },
      { year: 2013, champion: "Pat Thompson" },
      { year: 2012, champion: "Rick Cloninger" },
      { year: 2011, champion: "Paul Simson" },
      { year: 2010, champion: "Chip Lutz" },
      { year: 2009, champion: "Paul Simson" },
      { year: 2008, champion: "Rob Hess" },
      { year: 2007, champion: "Paul Simson" },
      { year: 2006, champion: "Paul Simson" },
      { year: 2005, champion: "David Brookreson" },
      { year: 2004, champion: "Berger Warner" },
      { year: 2003, champion: "Robert Kulp" },
      { year: 2002, champion: "William Boles, Jr." },
      { year: 2001, champion: "John Crooks" },
      { year: 2000, champion: "Robert Kulp" },
      { year: 1999, champion: "Mike Rice" },
      { year: 1998, champion: "Robert Kulp" },
      { year: 1997, champion: "Chip Stewart" },
      { year: 1996, champion: "Bill Cox" },
      { year: 1995, champion: "Deane Hundley" },
      { year: 1994, champion: "Bill Cox" },
      { year: 1993, champion: "Jim Kiem" },
      { year: 1992, champion: "Chuck Smith" },
      { year: 1991, champion: "Carey Schulte" },
      { year: 1990, champion: "Chuck Smith" },
      { year: 1989, champion: "Denis Biron" },
      { year: 1988, champion: "Moot Thomas" },
      { year: 1987, champion: "Gael Coakley" },
      { year: 1986, champion: "Joseph Fiason" },
      { year: 1985, champion: "Fred Zinn" },
      { year: 1984, champion: "Howard Derrick" },
      { year: 1983, champion: "Edward Ervasti" },
      { year: 1982, champion: "Brown McDonald" },
      { year: 1981, champion: "Richard Remsen" },
      { year: 1980, champion: "Dale Morey" },
      { year: 1979, champion: "Dale Morey" },
      { year: 1978, champion: "Edward Ervasti" },
      { year: 1977, champion: "George Pottle" },
      { year: 1976, champion: "Paul Severin" },
      { year: 1975, champion: "Harry L. Welch" },
      { year: 1974, champion: "David Goldman" },
      { year: 1973, champion: "Raymond Palmer" },
      { year: 1972, champion: "William Hyndman, III" },
      { year: 1971, champion: "David Goldman" },
      { year: 1970, champion: "Robert E. Cochran" },
      { year: 1969, champion: "Curtis Person" },
      { year: 1968, champion: "Curtis Person" },
      { year: 1967, champion: "Bob Cochran" },
      { year: 1966, champion: "Curtis Person" },
      { year: 1965, champion: "David Goldman" },
      { year: 1964, champion: "James H. McAlvin" },
      { year: 1963, champion: "James H. McAlvin" },
      { year: 1962, champion: "Col. Wm. K. Lanman" },
      { year: 1961, champion: "Robert R. Bell" },
      { year: 1960, champion: "Thomas C. Robbins" },
      { year: 1959, champion: "Walter F. Pease" },
      { year: 1958, champion: "J. Wolcott Brown" },
      { year: 1957, champion: "J. Wood Platt" },
      { year: 1956, champion: "Thomas C. Robbins" },
      { year: 1955, champion: "B. F. Kraffert, Jr." },
      { year: 1954, champion: "Spencer S. Overton" },
      { year: 1953, champion: "O. V. Russell" },
      { year: 1952, champion: "Judd L. Brumley" },
    ],
    howToPlay: [
      {
        label: "Exempt players: invitation",
        note: "Players meeting exemption criteria are invited and accepted upon official application, guaranteed a spot unless more than 90 exempt players accept in a division. In that case, entry is prioritized by exemption level (S1 before S2, and so on).",
      },
      {
        label: "Apply to Play",
        href: "https://www.pinehurst.com/golf/tournaments/north-south-senior-amateur/",
        note: "Players outside the exemption categories may formally apply, ideally with a playing resume; resumes and rankings are used to fill the remaining spots at the Championship Committee's discretion, and all decisions are final.",
      },
    ],
  },
  {
    slug: "valentine-invitational",
    name: "Valentine Invitational (Senior Division)",
    logo: "/brand/Valentine.jpeg",
    month: "August 2026",
    dates2026: "August 21-23, 2026",
    startDate: "2026-08-21",
    endDate: "2026-08-23",
    format: "54-hole stroke play",
    course: "Hermitage Country Club (Sabot & Manakin Courses)",
    location: "Richmond, VA",
    courseDesigner: "Ed Ault (1973); Arthur Hills renovation (2000)",
    tournamentWebsite: "https://thevalentineinvitational.com/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12338736295793668275",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Valentine Invitational is a premier Virginia senior and mid-amateur event held annually across Hermitage Country Club\u2019s Sabot and Manakin Courses in the rolling Goochland County countryside outside Richmond. The 54-hole stroke-play competition draws a national senior field each August, making it one of the Mid-Atlantic\u2019s most respected invitationals.",
    winners: [
      { year: 2026, champion: "Buck Brittain" },
      { year: 2025, champion: "Brian Quackenbush" },
      { year: 2024, champion: "Scott Shingler" },
      { year: 2023, champion: "Steve Serrao" },
      { year: 2022, champion: "Jon Hurst" },
      { year: 2021, champion: "Jon Hurst" },
      { year: 2020, champion: "Buck Brittain" },
      { year: 2019, champion: "David Partridge" },
      { year: 2018, champion: "Steve Liebler" },
      { year: 2017, champion: "Robert Nussey, Jr" },
      { year: 2016, champion: "Mike Krulich" },
      { year: 2015, champion: "David Partridge" },
      { year: 2014, champion: "Jim Gallagher" },
    ],
    howToPlay: [{ label: "Apply here", href: "https://www.golfgenius.com/pages/12338736307437056184" }],
  },
  {
    slug: "usga-mens-senior-amateur",
    name: "USGA Men's Senior Amateur",
    logo: "/brand/usga-mens-senior-amateur.png",
    month: "August/September 2026",
    liveStatus: "completed",
    startDate: "2026-08-29",
    endDate: "2026-09-03",
    dates2026: "Aug 29 – Sep 3, 2026",
    format: "stroke play + match play",
    course: "Baltimore Country Club (East Course)",
    location: "Lutherville, MD",
    coursePar: 70,
    courseYardage: 7181,
    courseDesigner: "A.W. Tillinghast (1926)",
    tournamentWebsite: "https://championships.usga.org/ussenioramateur.html",
    golfGeniusUrl: "https://championships.usga.org/ussenioramateur/2026/scoring.html",
    golfGeniusUrlLabel: "Live Scoring",
    note: "Rotating venue; 2026 host: Baltimore Country Club (East Course), Lutherville, MD",
    overview: "The USGA Men\u2019s Senior Amateur is America\u2019s most prestigious senior amateur title, contested annually since 1955 at rotating private courses nationwide. Open to amateurs 55+ with a Handicap Index of 5.4 or lower, the championship combines 36 holes of qualifying stroke play with match play elimination \u2014 mirroring the historic format of the U.S. Amateur.",
    winners: [
      { year: 2026, champion: "Mike Sposa" },
      { year: 2025, champion: "Mike McCoy" },
      { year: 2024, champion: "Louis Brown" },
      { year: 2023, champion: "Todd White" },
      { year: 2022, champion: "Rusty Strawn" },
      { year: 2021, champion: "Gene Elliott" },
      { year: 2019, champion: "Bob Royak" },
      { year: 2018, champion: "Jeff Wilson" },
      { year: 2017, champion: "Sean Knapp" },
      { year: 2016, champion: "Dave Ryan" },
      { year: 2015, champion: "Chip Lutz" },
      { year: 2014, champion: "Patrick Tallent" },
      { year: 2013, champion: "Doug Hanzel" },
      { year: 2012, champion: "Paul Simson" },
      { year: 2011, champion: "Louis Lee" },
      { year: 2010, champion: "Paul Simson" },
      { year: 2009, champion: "Vinny Giles" },
      { year: 2008, champion: "Buddy Marucci" },
      { year: 2007, champion: "Stan Lee" },
      { year: 2006, champion: "Mike Bell" },
      { year: 2005, champion: "Mike Rice" },
      { year: 2004, champion: "Mark Bemowski" },
      { year: 2003, champion: "Kemp Richardson" },
      { year: 2002, champion: "Greg Reynolds" },
      { year: 2001, champion: "Kemp Richardson" },
      { year: 2000, champion: "Bill Shean Jr." },
      { year: 1999, champion: "Bill Ploeger" },
      { year: 1998, champion: "Bill Shean Jr." },
      { year: 1997, champion: "Cliff Cunningham" },
      { year: 1996, champion: "O. Gordon Brewer Jr." },
      { year: 1995, champion: "James Stahl Jr." },
      { year: 1994, champion: "O. Gordon Brewer Jr." },
      { year: 1993, champion: "Joe Ungvary" },
      { year: 1992, champion: "Clarence Moore" },
      { year: 1991, champion: "Bill Bosshard" },
      { year: 1990, champion: "Jackie Cummings" },
      { year: 1989, champion: "R. S. Williams" },
      { year: 1988, champion: "Clarence Moore" },
      { year: 1987, champion: "John Richardson" },
      { year: 1986, champion: "R. S. Williams" },
      { year: 1985, champion: "Lewis Oehmig" },
      { year: 1984, champion: "Robert Rawlins" },
      { year: 1983, champion: "Bill Hyndman" },
      { year: 1982, champion: "Alton Duhon" },
      { year: 1981, champion: "Ed Updegraff" },
      { year: 1980, champion: "William C. Campbell" },
      { year: 1979, champion: "William C. Campbell" },
      { year: 1978, champion: "Keith K. Compton" },
      { year: 1977, champion: "Dale Morey" },
      { year: 1976, champion: "Lewis Oehmig" },
      { year: 1975, champion: "William F. Colm" },
      { year: 1974, champion: "Dale Morey" },
      { year: 1973, champion: "Bill Hyndman" },
      { year: 1972, champion: "Lewis Oehmig" },
      { year: 1971, champion: "Tom Draper" },
      { year: 1970, champion: "Gene Andrews" },
      { year: 1969, champion: "Curtis Person, Sr." },
      { year: 1968, champion: "Curtis Person, Sr." },
      { year: 1967, champion: "Ray Palmer" },
      { year: 1966, champion: "Dexter H. Daniels" },
      { year: 1965, champion: "Robert B. Kiersky" },
      { year: 1964, champion: "William D. Higgins" },
      { year: 1963, champion: "Merrill L. Carlsmith" },
      { year: 1962, champion: "Merrill L. Carlsmith" },
      { year: 1961, champion: "Dexter H. Daniels" },
      { year: 1960, champion: "Michael Cestone" },
      { year: 1959, champion: "J. Clark Espie" },
      { year: 1958, champion: "Thomas C. Robbins" },
      { year: 1957, champion: "J. Clark Espie" },
      { year: 1956, champion: "Fred Wright" },
      { year: 1955, champion: "J. Wood Platt" },
    ],
    howToPlay: [{ label: "Open qualifying + exemptions", href: "https://champ-admin.usga.org/player" }],
  },
  {
    slug: "senior-porter-cup",
    name: "Senior Porter Cup",
    month: "September 2026",
    startDate: "2026-09-09",
    endDate: "2026-09-11",
    format: "54-hole stroke play",
    course: "Niagara Falls Country Club",
    location: "Lewiston, NY",
    coursePar: 70,
    courseYardage: 6621,
    courseDesigner: "A.W. Tillinghast (1919)",
    tournamentWebsite: "https://www.portercup.com/project-1-1",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12486243992301746262",
    golfGeniusUrlLabel: "Live Scoring",
    overview: "The Senior Porter Cup is a standalone spinoff of the prestigious Porter Cup Invitational, held at historic Niagara Falls Country Club \u2014 an A.W. Tillinghast design from 1919 set atop the bluffs above the Niagara River. The event features four age divisions (Senior 55+, Super Senior 65+, Legends 70+, Super Legends 75+) and draws elite older amateurs to western New York each September.",
    pastResults: [
      { year: 2025, champion: "Howard Clendenin", score: "209" },
      { year: 2024, champion: "Dave Bunker", score: "210" },
      { year: 2023, champion: "Rick Stimmel", score: "213" },
      { year: 2022, champion: "Kevin Vandenberg", score: "139" },
      { year: 2021, champion: "Steve Maddalena", score: "208" },
      { year: 2019, champion: "Doug Hanzel", score: "204" },
      { year: 2018, champion: "Keith Decker", score: "216" },
      { year: 2017, champion: "Keith Decker", score: "137" },
      { year: 2016, champion: "Keith Decker", score: "206" },
      { year: 2015, champion: "Doug Hanzel", score: "204" },
      { year: 2014, champion: "Don Kuehn (54 holes)", score: "140" },
      { year: 2013, champion: "Ted Smith", score: "217" },
      { year: 2012, champion: "Fred Silver", score: "213" },
      { year: 2011, champion: "Skip Snow", score: "213" },
      { year: 2010, champion: "Gary Shimmin", score: "221" },
      { year: 2009, champion: "Gary Cloutier", score: "215" },
      { year: 2008, champion: "Rich Anderson", score: "214" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "crump-cup-senior-division",
    name: "The Crump Cup (Senior Division)",
    month: "September 2026",
    dates2026: "September 17-20, 2026",
    startDate: "2026-09-17",
    endDate: "2026-09-20",
    format: "stroke play",
    course: "Pine Valley Golf Club",
    location: "Pine Valley, NJ",
    coursePar: 70,
    courseYardage: 7197,
    courseDesigner: "George Crump (1919)",
    overview: "The Crump Cup has been contested at Pine Valley Golf Club since 1922 \u2014 the year of the course\u2019s formal opening \u2014 and is one of amateur golf\u2019s most exclusive invitations. Played on what is consistently ranked the world\u2019s finest golf course, the senior division runs concurrently with the mid-amateur flight, offering a rare chance to compete at this famously private New Jersey club.",
    winners: [
      { year: 2025, champion: "Bob Royak" },
      { year: 2024, champion: "Matthew Sughrue" },
      { year: 2022, champion: "Tommy Brennan" },
      { year: 2019, champion: "Gene Elliott" },
      { year: 2017, champion: "John McClure" },
      { year: 2016, champion: "Jim Lehman" },
      { year: 2013, champion: "Gene Elliott" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "international-senior-individual-championship",
    name: "International Senior Individual Championship",
    month: "October 2026",
    startDate: "2026-10-12",
    endDate: "2026-10-15",
    format: "54-hole stroke play",
    golfGeniusUrl: "https://www.amateurgolfinfo.com/events/mens/international-senior-individual-championship-67/400",
    golfGeniusUrlLabel: "2025 Results",
    overview: "The International Senior Individual Championship is an elite 54-hole stroke-play event on the global senior amateur calendar, drawing invited players from multiple countries to compete as individuals. The format provides an international stage for the world\u2019s top 55+ amateurs and complements national team senior competitions.",
    winners: [
      { year: 2025, champion: "Joe Lyons" },
      { year: 2024, champion: "Doug Hanzel" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "ojai-senior-cup",
    name: "Ojai Senior Cup",
    logo: "/brand/ojailogo.png",
    month: "October 2026",
    dates2026: "October 16-18, 2026",
    startDate: "2026-10-16",
    endDate: "2026-10-18",
    format: "54-hole stroke play",
    course: "Soule Park Golf Course",
    location: "Ojai, CA",
    coursePar: 72,
    courseYardage: 6475,
    courseDesigner: "William F. Bell Jr. (1962); Gil Hanse renovation (2006)",
    tournamentWebsite: "https://www.ojaiseniorcup.com/",
    golfGeniusUrl: "https://2025ojaiseniorcup.golfgenius.com/pages/5274295",
    golfGeniusUrlLabel: "2025 Results",
    overview: "The Ojai Senior Cup is the West Coast\u2019s premier senior amateur championship, held annually at the historic Soule Park Golf Course in the Ojai Valley north of Santa Barbara. The public course \u2014 renovated by Gil Hanse in 2006 \u2014 winds through towering oaks in the scenic Topatopa Mountains, featuring senior (55+) and super senior (65+) divisions over 54 holes.",
    winners: [
      { year: 2025, champion: "Tim Hogarth" },
      { year: 2024, champion: "Tim Hogarth" },
      { year: 2023, champion: "Gregory Sato" },
      { year: 2022, champion: "Craig Steinberg" },
      { year: 2021, champion: "Steven McPherson" },
      { year: 2020, champion: "Daniel Sullivan" },
      { year: 2019, champion: "Tim Hogarth" },
    ],
    howToPlay: [
      {
        label: "Eligibility",
        note: "Senior Division: 55+ by October 16, 2026, max 6.5 Handicap Index. Super Senior Division: 65+ by October 16, 2026, max 8.5 Handicap Index.",
      },
      {
        label: "Register here",
        href: "https://www.golfgenius.com/pages/5929750",
        note: "Registration opens April 1, 2026 and stays open through September 30 for remaining spots or the waitlist. Past champions, top-15 (Senior) and top-5 (Super Senior) finishers from 2025, top-ranked WAGR/SCGA/NCGA seniors, and 2024-2026 U.S. Senior Amateur/Open qualifiers are guaranteed entry; other pending registrations are reviewed by June 30.",
      },
    ],
  },
  {
    slug: "reynolds-senior-invitational",
    name: "Reynolds Senior Invitational",
    month: "October 2026",
    startDate: "2026-10-26",
    endDate: "2026-10-28",
    format: "54-hole stroke play",
    course: "Great Waters Course at Reynolds Lake Oconee",
    location: "Greensboro, GA",
    courseDesigner: "Jack Nicklaus (1992)",
    golfGeniusUrl: "https://www.societyofseniors.com/wp-content/uploads/2025/10/reynolds_2025_results.pdf",
    golfGeniusUrlLabel: "2025 Results",
    overview: "The Reynolds Senior Invitational is an elite invitation-only event held at Reynolds Lake Oconee in the Georgia countryside. The Jack Nicklaus-designed Great Waters course provides a championship-caliber setting for the 54-hole stroke-play competition, which features senior, super senior, legend, and grand master age divisions.",
    winners: [
      { year: 2025, champion: "Bob Royak" },
      { year: 2024, champion: "Jack Larkin" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "california-senior-amateur",
    name: "California Senior Amateur Championship",
    logo: "/brand/calamlogo.png",
    month: "November 2026",
    startDate: "2026-11-09",
    endDate: "2026-11-11",
    course: "Serrano Country Club",
    location: "El Dorado Hills, CA",
    format: "54-hole stroke play",
    tournamentWebsite: "https://calam-2026californiasenioramateur.golfgenius.com/pages/12206054641741353670",
    golfGeniusUrl: "https://calam-2025californiasenioramateurchampio.golfgenius.com/pages/11191140202976400081",
    golfGeniusUrlLabel: "2025 Results",
    note: "Rotating venue: northern CA courses in even years, southern CA courses in odd years",
    overview: "The California Senior Amateur Championship is the state\u2019s premier senior title, co-conducted by the SCGA and NCGA and rotating between northern and southern California venues. Past hosts include Poppy Hills Golf Course, Ojai Valley Inn, and The Valley Club at Montecito, with northern courses hosting in even years and southern in odd years.",
    pastResults: [
      { year: 2025, champion: "Bob Niger", venue: "Valley Club at Montecito", score: "205" },
      { year: 2024, champion: "Trae Cassell", venue: "Monterey Peninsula CC", score: "214" },
      { year: 2023, champion: "Craig Davis", venue: "Red Hill CC", score: "212" },
      { year: 2022, champion: "Randy Haag", venue: "Pasatiempo GC", score: "213" },
      { year: 2021, champion: "Randy Haag", venue: "Hillcrest CC", score: "210" },
      { year: 2020, champion: "Robert Funk", venue: "Poppy Hills", score: "211" },
      { year: 2019, champion: "Casey Boyns", venue: "Wilshire CC", score: "215" },
      { year: 2018, champion: "Jeff Wilson", venue: "The Preserve GC", score: "212" },
      { year: 2017, champion: "Mark Morgan", venue: "Pauma Valley CC", score: "212" },
      { year: 2016, champion: "John Pate", venue: "Lake Merced GC", score: "216" },
      { year: 2015, champion: "Mark Harding", venue: "Mesa Verde CC", score: "209" },
      { year: 2014, champion: "John Pate", venue: "Poppy Hills GC", score: "214" },
      { year: 2013, champion: "Jim Knoll", venue: "San Gabriel CC", score: "212" },
      { year: 2012, champion: "Casey Boyns", venue: "Del Rio CC", score: "219" },
      { year: 2011, champion: "Mark Nickeas", venue: "Saticoy CC", score: "221" },
      { year: 2010, champion: "Jeff Burda", venue: "Ft. Washington CC", score: "211" },
      { year: 2009, champion: "Jeff Burda", venue: "Poppy Hills GC", score: "211" },
      { year: 2008, champion: "Jeff Burda", venue: "Poppy Hills GC", score: "209" },
      { year: 2007, champion: "Gary Vanier", venue: "Poppy Hills GC", score: "221" },
      { year: 2006, champion: "Steve Bogan", venue: "Poppy Hills GC", score: "224" },
      { year: 2005, champion: "Bob Olds", venue: "Poppy Hills GC", score: "219" },
      { year: 2004, champion: "Rob Thompson", venue: "Poppy Hills GC", score: "218" },
      { year: 2003, champion: "Joe Dudley", venue: "Poppy Hills GC", score: "220" },
      { year: 2002, champion: "Ted Lyford", venue: "Poppy Hills GC", score: "211" },
      { year: 2001, champion: "Roly Lamontagne", venue: "Poppy Hills", score: "214" },
      { year: 2000, champion: "Mike Riley", venue: "Poppy Hills GC", score: "221" },
      { year: 1999, champion: "Tom Eastlack", venue: "Poppy Hills GC", score: "220" },
      { year: 1998, champion: "Jim McMurtrey", venue: "Poppy Hills GC", score: "219" },
      { year: 1997, champion: "Cliff Davis", venue: "Poppy Hills GC", score: "218" },
      { year: 1996, champion: "Paul Spengler", venue: "Poppy Hills GC", score: "224" },
      { year: 1995, champion: "Jim McMurtrey", venue: "Poppy Hills GC", score: "219" },
      { year: 1994, champion: "Jim McMurtrey", venue: "Poppy Hills GC", score: "218" },
      { year: 1993, champion: "Paul Ladin", venue: "Ojai Valley Inn", score: "142" },
      { year: 1992, champion: "Chuck Weil", venue: "Ojai Valley Inn", score: "142" },
    ],
    howToPlay: [{ label: "Register here", href: "https://calam-2026californiasenioramateur.golfgenius.com/pages/12206054641741353670" }],
  },
  {
    slug: "society-of-seniors-ralph-bogart",
    name: "Society of Seniors: Ralph Bogart",
    tournamentWebsite: "https://www.societyofseniors.com/",
    logo: "/brand/society-of-seniors.jpg",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5211625",
    golfGeniusUrlLabel: "2025 Results",
    month: "November 2026",
    startDate: "2026-11-09",
    endDate: "2026-11-11",
    format: "54-hole stroke play",
    course: "Hammock Beach Resort (Conservatory Course)",
    location: "Palm Coast, FL",
    note: "Rotating venue; recent hosts: Hammock Beach Resort, Palm Coast, FL (2025); Abacoa GC, Jupiter, FL (2024)",
    overview: "The SOS Ralph Bogart Tournament is named for Ralph Bogart, co-founder of the Society of Seniors in 1983. The 54-hole stroke-play event typically closes the fall portion of the SOS annual schedule, rotating among Florida\u2019s premier resort venues and crowning champions across four age divisions.",
    pastResults: [
      { year: 2025, champion: "Rick Stimmel", venue: "The Conservatory at Hammock Beach" },
      { year: 2024, champion: "Gene Elliott", venue: "Abacoa Golf Club" },
      { year: 2023, champion: "Rick Stimmel", venue: "Innisbrook Resort (Copperhead Course)" },
      { year: 2022, champion: "Doug Hanzel", venue: "North Palm Beach CC" },
      { year: 2021, champion: "Rusty Strawn", venue: "Crown Colony Golf & CC" },
      { year: 2020, champion: "Rusty Strawn", venue: "The Forest & Crown Colony Golf & CC" },
      { year: 2019, champion: "Doug Hanzel", venue: "Bear Lakes CC" },
      { year: 2018, champion: "Jack Kearney", venue: "Hammock Bay Golf & CC" },
      { year: 2017, champion: "Rick Woulfe", venue: "Harbour Ridge Yacht & CC" },
      { year: 2016, champion: "Jack Kearney", venue: "Crown Colony Golf & CC" },
      { year: 2015, champion: "KC Fox", venue: "Crown Colony Golf & CC" },
      { year: 2014, champion: "Rick Woulfe", venue: "Old Trail GC" },
      { year: 2013, champion: "Bob Stephens", venue: "The Forest CC" },
      { year: 2012, champion: "Chip Lutz", venue: "The Fox Club" },
      { year: 2011, champion: "Chip Lutz", venue: "John's Island GC" },
      { year: 2010, champion: "Bill Zlystra", venue: "Old Trail GC" },
      { year: 2009, champion: "Bill Zlystra", venue: "The Verandah Club" },
      { year: 2008, champion: "Pat Talent", venue: "The Club at Mediterra" },
      { year: 2007, champion: "Bill Zylstra", venue: "The Club at Twin Eagles" },
      { year: 2006, champion: "Rick Woulfe", venue: "The Club at Twin Eagles" },
      { year: 2005, champion: "Mike Bell", venue: "The Club at Twin Eagles" },
      { year: 2004, champion: "Mike Bell", venue: "The Club at Twin Eagles" },
      { year: 2003, champion: "Jack Richey", venue: "The Club at Twin Eagles" },
      { year: 2002, champion: "James Snow", venue: "The Club at Twin Eagles" },
      { year: 2001, champion: "Bob Hullender", venue: "Bonita Bay Club" },
      { year: 2000, champion: "Curtis Madsen", venue: "Bonita Bay Club" },
      { year: 1999, champion: "Bob Hullender", venue: "Bonita Bay Club" },
      { year: 1998, champion: "Bob Hullender", venue: "Bonita Bay Club" },
      { year: 1997, champion: "Bob Hullender", venue: "Bonita Bay Club" },
      { year: 1996, champion: "Bob Hullender", venue: "Riverwood CC" },
      { year: 1995, champion: "John Ward", venue: "Southern Dunes" },
      { year: 1994, champion: "Bob Hullender", venue: "Loxahatchee Club" },
      { year: 1993, champion: "Tom Watrous", venue: "Old Trail GC" },
      { year: 1992, champion: "Bob Miller", venue: "Old Trail GC" },
      { year: 1991, champion: "Bob Miller", venue: "Old Trail GC" },
      { year: 1990, champion: "John Pottle", venue: "Old Trail GC" },
      { year: 1989, champion: "Bob Hardy", venue: "Old Marsh GC" },
      { year: 1988, champion: "Dale Morey", venue: "Old Marsh GC" },
      { year: 1987, champion: "Jack Hesler", venue: "Palm Beach Polo" },
      { year: 1986, champion: "Clarence Moore", venue: "St. Andrews CC" },
      { year: 1985, champion: "Fritz Franz", venue: "St. Andrews CC" },
      { year: 1984, champion: "Dale Morey", venue: "St. Andrews CC" },
    ],
    howToPlay: [{ label: "Apply for invite", href: "https://www.societyofseniors.com/membership/" }],
  },
  {
    slug: "east-west-cup-matches",
    name: "East West Cup Matches",
    month: "November 2026",
    startDate: "2026-11-16",
    endDate: "2026-11-18",
    format: "team matches",
    course: "Maridoe Golf Club",
    location: "Carrollton, TX",
    overview: "The East West Cup Matches pits an elite team from west of the Mississippi against a team from the east in a Ryder Cup-style team competition. Each side fields 18 players drawn from senior, mid-amateur, and young amateur ranks, and the event is primarily hosted at Maridoe Golf Club in Carrollton, Texas \u2014 one of America\u2019s most demanding private courses.",
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "giles-invitational-senior-division",
    name: "The Giles Invitational (Senior Division)",
    logo: "/brand/Kinloch.jpeg",
    month: "May 2026",
    startDate: "2026-05-01",
    endDate: "2026-05-03",
    format: "54-hole stroke play",
    course: "Kinloch Golf Club",
    location: "Manakin-Sabot, VA",
    coursePar: 72,
    courseYardage: 7373,
    courseDesigner: "Lester George",
    tournamentWebsite: "https://www.amateurgolfinfo.com/events/mens/the-giles-invitational---senior-694/1092",
    tournamentWebsiteLabel: "Data Source",
    golfGeniusUrl: "https://www.golfgenius.com/pages/11897323631677564724",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Giles Invitational runs a senior division alongside its mid-amateur field at Kinloch Golf Club, honoring amateur legend Vinny Giles on the course he co-designed with Lester George. The event has quickly built a reputation as one of the more competitive new stops on the calendar since its 2025 debut.",
    winners: [
      { year: 2026, champion: "Rick Stimmel" },
      { year: 2025, champion: "Matt Sughrue" },
    ],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "jupiter-invitational-senior-division",
    name: "The Jupiter Invitational (Senior Division)",
    logo: "/brand/Jupiter.jpg",
    month: "May 2026",
    startDate: "2026-05-07",
    endDate: "2026-05-09",
    format: "54-hole stroke play",
    course: "Jonathan\u2019s Landing Golf Club (Match Course at Old Trail)",
    location: "Jupiter, FL",
    coursePar: 70,
    courseYardage: 6500,
    courseDesigner: "Gil Hanse & Jim Wagner (2021 redesign of Arthur Hills original)",
    tournamentWebsite: "https://www.golfgenius.com/pages/12681244252160674003",
    golfGeniusUrl: "https://www.golfgenius.com/pages/11637199273677834597",
    golfGeniusUrlLabel: "2026 Results",
    overview: "The Jupiter Invitational pairs its mid-amateur field with a senior division on the Gil Hanse-redesigned Match Course at Jonathan\u2019s Landing. The curated, invitation-only event debuted in 2026 and quickly drew a competitive South Florida field across both divisions.",
    winners: [{ year: 2026, champion: "Mike McCoy" }],
    howToPlay: [{ label: "Apply for invite", href: "https://www.golfgenius.com/register?league_id=11637199223413295215" }],
  },
  {
    slug: "walter-j-travis-invitational-senior-division",
    name: "The Walter J. Travis Invitational (Senior Division)",
    logo: "/brand/Walter Travis.jpeg",
    month: "May 2026",
    startDate: "2026-05-15",
    endDate: "2026-05-17",
    format: "Match play",
    course: "Garden City Golf Club",
    location: "Garden City, NY",
    coursePar: 73,
    courseYardage: 6926,
    courseDesigner: "Devereux Emmet",
    overview: "The Walter J. Travis Invitational runs the Eisenhower Cup as its senior match-play flight alongside the Championship Flight at historic Garden City Golf Club. Named for Walter J. Travis, the British Amateur and three-time U.S. Amateur champion who called Garden City home, the event is one of the most storied match-play invitations on the calendar.",
    winners: [{ year: 2026, champion: "Dave Scialabba" }],
    howToPlay: [{ label: "Invite only \u2014 no application" }],
  },
  {
    slug: "national-senior-hall-of-fame",
    name: "National Senior Amateur Hall of Fame",
    month: "June 2026",
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    course: "High Point Country Club (Willow Creek Course)",
    location: "High Point, NC",
    tournamentWebsite: "https://www.nsahof.com/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/12747802768916353340",
    golfGeniusUrlLabel: "2026 Results",
    howToPlay: [{ label: "Apply for invite here", href: "https://www.nsahof.com/tournament/entry-form" }],
    winners: [
      { year: 2026, champion: "Vance Welch" },
      { year: 2025, champion: "Greg Sanders" },
      { year: 2024, champion: "Randy Haag" },
      { year: 2023, champion: "Joe Jaspers" },
      { year: 2022, champion: "Doug Hanzel" },
      { year: 2021, champion: "Bob Royak" },
      { year: 2019, champion: "Steve Harwell" },
      { year: 2018, champion: "Jack Hall" },
      { year: 2017, champion: "Doug Hanzel" },
      { year: 2016, champion: "Doug Hanzel" },
      { year: 2015, champion: "Rick Cloninger" },
      { year: 2014, champion: "Chip Lutz" },
      { year: 2013, champion: "Paul Simson" },
      { year: 2012, champion: "Paul Simson" },
      { year: 2011, champion: "Stan Lee" },
      { year: 2010, champion: "Paul Simson" },
      { year: 2009, champion: "Ted Smith" },
      { year: 2008, champion: "Paul Simson" },
      { year: 2007, champion: "Ron Carter" },
      { year: 2006, champion: "Mike Rice" },
      { year: 2005, champion: "Larry Clark" },
      { year: 2004, champion: "David Carroll" },
      { year: 2003, champion: "Jamie Gough" },
      { year: 2002, champion: "Edward Craig" },
      { year: 2001, champion: "Spencer Sappington" },
      { year: 2000, champion: "Woody Greene" },
      { year: 1999, champion: "Bob Hullender" },
      { year: 1998, champion: "Tom Hadley" },
      { year: 1997, champion: "O.Gordon Brewer" },
      { year: 1996, champion: "Ted Gaston" },
      { year: 1995, champion: "Richard Tatum" },
      { year: 1994, champion: "Rennie Law" },
      { year: 1993, champion: "Chuck Smith" },
      { year: 1992, champion: "Chuck Smith" },
      { year: 1991, champion: "Tommy Langley" },
      { year: 1990, champion: "Tommy Langley" },
      { year: 1989, champion: "Bo Williams" },
      { year: 1988, champion: "Bo Williams" },
      { year: 1987, champion: "Sonny Grant" },
      { year: 1986, champion: "Jim Frost" },
      { year: 1985, champion: "Robert S. Rawlins" },
      { year: 1984, champion: "Don Adderton" },
    ],
  },
  {
    slug: "golfweek-senior-national-championship",
    name: "Golfweek Senior National Championship",
    logo: "/brand/GwkSrNation_BADGE.svg",
    tournamentWebsite: "https://golfweekseniornation.com/",
    month: "June 2026",
    startDate: "2026-06-15",
    endDate: "2026-06-17",
    course: "Benvenue Golf & Country Club",
    location: "Rocky Mount, NC",
    winners: [{ year: 2026, champion: "Bryan Hoops" }],
  },
  {
    slug: "george-c-thomas-invitational-senior-division",
    name: "George C. Thomas Invitational (Senior Division)",
    logo: "/brand/LACC.jpeg",
    month: "June 2026",
    startDate: "2026-06-25",
    endDate: "2026-06-27",
    format: "54-hole stroke play",
    course: "Los Angeles Country Club",
    location: "Los Angeles, CA",
    coursePar: 71,
    courseYardage: 7530,
    courseDesigner: "George C. Thomas Jr.",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5747293",
    overview: "The George C. Thomas Invitational runs a senior division alongside its mid-amateur field at Los Angeles Country Club, site of the 2023 U.S. Open. The stroke-play event is one of the most sought-after invitations in West Coast amateur golf.",
    winners: [{ year: 2026, champion: "Bryan Hoops" }],
    howToPlay: [{ label: "Invite only — no application" }],
  },
  {
    slug: "golfweek-senior-tournament-of-champions",
    name: "Golfweek Senior Tournament of Champions",
    logo: "/brand/GwkSrNation_BADGE.svg",
    tournamentWebsite: "https://golfweekseniornation.com/",
    month: "December 2026",
    startDate: "2026-12-05",
    endDate: "2026-12-07",
    course: "PGA National Resort & Spa (Fazio Course)",
    location: "West Palm Beach, FL",
    howToPlay: [{ label: "Open signup — no application" }],
  },
  {
    slug: "golfweek-senior-desert-showdown",
    name: "Golfweek Senior Desert Showdown",
    logo: "/brand/GwkSrNation_BADGE.svg",
    tournamentWebsite: "https://golfweekseniornation.com/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/11649874220149642639",
    golfGeniusUrlLabel: "2025 Results",
    month: "November 2026",
    startDate: "2026-11-02",
    endDate: "2026-11-04",
    course: "Boulder Creek Golf Club",
    location: "Las Vegas, NV",
    winners: [{ year: 2025, champion: "Jerry Gunthorpe" }],
    howToPlay: [{ label: "Apply to Play", href: "https://www.golfgenius.com/pages/12693592928455496898" }],
  },
  {
    slug: "carlton-woods-senior-invitational",
    name: "Carlton Woods Senior Invitational",
    month: "October 2026",
    startDate: "2026-10-26",
    endDate: "2026-10-28",
    course: "The Club at Carlton Woods",
    location: "The Woodlands, TX",
    tournamentWebsite: "https://carltonwoodsinvitational.com/",
    golfGeniusUrl: "https://carltonwoodsinvitational.com/results/",
    golfGeniusUrlLabel: "2025 Results",
    winners: [
      { year: 2024, champion: "Mark Strickland" },
      { year: 2022, champion: "Robert Funk" },
      { year: 2021, champion: "David Ortega" },
      { year: 2019, champion: "Lewis Stephenson" },
      { year: 2018, champion: "Mike Booker" },
      { year: 2017, champion: "Jeff New" },
      { year: 2016, champion: "Lewis Stephenson" },
      { year: 2015, champion: "Lee Sandlin" },
      { year: 2014, champion: "Mike Booker" },
      { year: 2013, champion: "Doug Pool" },
      { year: 2012, champion: "Mike Booker" },
      { year: 2011, champion: "Mike Booker" },
      { year: 2010, champion: "Mike Bell" },
      { year: 2009, champion: "John Pigg" },
      { year: 2008, champion: "John Grace" },
      { year: 2007, champion: "Bob Hullender" },
      { year: 2006, champion: "Bob Hullender" },
    ],
    howToPlay: [{ label: "Register here", href: "https://www.golfgenius.com/register?league_id=12399398994642508996" }],
  },
  {
    slug: "dixie-senior-amateur",
    name: "Dixie Senior Amateur",
    month: "December 2026",
    startDate: "2026-12-09",
    endDate: "2026-12-11",
    course: "TPC Eagle Trace",
    location: "Coral Springs, FL",
    howToPlay: [{ label: "Open signup — no application" }],
  },
  {
    slug: "society-of-seniors-dale-morey",
    name: "Society of Seniors: Dale Morey Championship",
    logo: "/brand/society-of-seniors.jpg",
    tournamentWebsite: "https://www.societyofseniors.com/",
    golfGeniusUrl: "https://www.golfgenius.com/pages/5200469",
    golfGeniusUrlLabel: "2025 Results",
    month: "September 2026",
    startDate: "2026-09-28",
    endDate: "2026-09-30",
    course: "The Landings Golf & Athletic Club (Deer Creek Course)",
    location: "Savannah, GA",
    note: "Rotating venue; 2026 host: The Landings Golf & Athletic Club (Deer Creek Course), Savannah, GA",
    pastResults: [
      { year: 2025, champion: "Timothy Cobb", venue: "Innisbrook Resort (Copperhead Course)" },
      { year: 2024, champion: "Stan Humphries", venue: "Treyburn Country Club" },
      { year: 2023, champion: "Jack Hall", venue: "Berkeley Hall Club" },
      { year: 2022, champion: "Rusty Strawn", venue: "Pine Needles Resort" },
      { year: 2021, champion: "Rusty Strawn", venue: "Innisbrook Golf Resort" },
      { year: 2020, champion: "Daniel Russo", venue: "The Club at Quail Ridge" },
      { year: 2019, champion: "Doug Hanzel", venue: "Pine Needles & Mid Pines" },
      { year: 2018, champion: "Doug Hanzel", venue: "The Landings Club" },
      { year: 2017, champion: "Allen Barber", venue: "Innisbrook Golf Resort" },
      { year: 2016, champion: "Keith Decker", venue: "Pine Needles & Mid Pines" },
      { year: 2015, champion: "Bob Kearney", venue: "The Wigwam" },
      { year: 2014, champion: "Rick Woulfe", venue: "Quail Ridge CC (North & South)" },
      { year: 2013, champion: "Doug Hanzel", venue: "The Landings Club" },
      { year: 2012, champion: "Sam Till", venue: "Fiddlesticks CC" },
      { year: 2011, champion: "Paul Simson", venue: "Pine Needles & Mid Pines" },
      { year: 2010, champion: "Ron Carter", venue: "Quail Ridge CC (North & South)" },
      { year: 2009, champion: "Paul Simson", venue: "The Honors Course & Lookout Mountain" },
      { year: 2008, champion: "Jerry Hudgins", venue: "Twin Eagles and Bonita Bay East" },
      { year: 2007, champion: "Jay Blumenfeld", venue: "Fiddlesticks CC" },
      { year: 2006, champion: "Rick Woulfe", venue: "Quail Ridge CC (North & South)" },
      { year: 2005, champion: "Jerry Hudgins", venue: "World Golf Village" },
      { year: 2004, champion: "Ed Fletcher", venue: "The Hermitage GC" },
      { year: 2003, champion: "Spencer Sappington", venue: "Casino Magic, The Oaks CC" },
      { year: 2002, champion: "Vinny Giles", venue: "Quail Ridge CC (North & South)" },
      { year: 2001, champion: "Jerry Greenbaum", venue: "Emerald Dunes/Polo Trace" },
      { year: 2000, champion: "Bill Ploeger", venue: "Long Cove/Belfair-East" },
      { year: 1999, champion: "Joel Hirsch", venue: "Quail Ridge CC (North & South)" },
      { year: 1998, champion: "Joel Hirsch", venue: "Long Cove/Indigo Run" },
      { year: 1997, champion: "Jerry Nelson", venue: "Pine Needles & Mid Pines" },
      { year: 1996, champion: "Tom Hadley", venue: "Long Cove/Belfair" },
      { year: 1995, champion: "Bob Hullender", venue: "Dataw Island Club" },
      { year: 1994, champion: "Ward Wettlaufer", venue: "Long Cove/Colleton River" },
      { year: 1993, champion: "Chuck Smith", venue: "Amelia Island Plantation" },
      { year: 1992, champion: "Jim McMurtrey", venue: "Long Cove/Colleton River" },
      { year: 1991, champion: "Jim McMurtrey", venue: "Amelia Island Plantation" },
      { year: 1990, champion: "Billy Key", venue: "Long Cove/Harbor Town" },
      { year: 1989, champion: "Billy Key", venue: "Amelia Island Plantation" },
      { year: 1988, champion: "Joe Simpson", venue: "Long Cove/Moss Creek" },
      { year: 1987, champion: "Bo Williams", venue: "Long Cove/Moss Creek" },
      { year: 1986, champion: "Ed Tutwiler", venue: "Long Cove/Moss Creek" },
      { year: 1985, champion: "Keith Compton", venue: "Long Cove/Moss Creek" },
      { year: 1984, champion: "Bob Rawlins", venue: "Long Cove" },
      { year: 1983, champion: "Jack Van Ess", venue: "Long Cove" },
    ],
    howToPlay: [{ label: "Exempt categories + open qualifiers", href: "https://www.societyofseniors.com/" }],
  },
];

export function getSeniorMajorBySlug(slug: string): SeniorMajorEvent | null {
  return SENIOR_MAJOR_EVENTS_2026.find((e) => e.slug === slug) ?? null;
}

// Returns {tournament, article} for a given tournament slug + article slug, or undefined.
export function getSeniorMajorArticle(
  tournamentSlug: string,
  articleSlug: string
) {
  const tournament = getSeniorMajorBySlug(tournamentSlug);
  if (!tournament || !tournament.news) return undefined;
  const article = tournament.news.find((a) => a.slug === articleSlug);
  if (!article) return undefined;
  return { tournament, article };
}

// Returns all (tournamentSlug, articleSlug) pairs for static generation + sitemap.
export function listSeniorMajorArticleParams(): {
  slug: string;
  article: string;
}[] {
  const out: { slug: string; article: string }[] = [];
  for (const t of SENIOR_MAJOR_EVENTS_2026) {
    if (!t.news) continue;
    for (const a of t.news) {
      out.push({ slug: t.slug, article: a.slug });
    }
  }
  return out;
}

export function listSeniorMajorSlugs(): string[] {
  return SENIOR_MAJOR_EVENTS_2026.map((e) => e.slug);
}

export function listSeniorMajorsByMonth(): Array<{
  month: string;
  monthKey: string;
  events: SeniorMajorEvent[];
}> {
  const order = [
    "January 2026", "February 2026", "March 2026", "March/April 2026",
    "April 2026", "May 2026", "June 2026", "July 2026",
    "August 2026", "August/September 2026", "September 2026",
    "October 2026", "November 2026", "December 2026",
  ];
  const groups = new Map<string, SeniorMajorEvent[]>();
  for (const e of SENIOR_MAJOR_EVENTS_2026) {
    const arr = groups.get(e.month) || [];
    arr.push(e);
    groups.set(e.month, arr);
  }
  const out: Array<{ month: string; monthKey: string; events: SeniorMajorEvent[] }> = [];
  for (const m of order) {
    const events = groups.get(m);
    if (!events || !events.length) continue;
    const sorted = [...events].sort((a, b) => {
      if (!a.startDate) return b.startDate ? 1 : 0;
      if (!b.startDate) return -1;
      return a.startDate.localeCompare(b.startDate);
    });
    const monthKey = m.split(" ")[0].slice(0, 3).toLowerCase();
    out.push({ month: m, monthKey, events: sorted });
  }
  return out;
}


// Returns the senior tournament(s) to show in the "Now playing" / "Up next"
// widget on the seniorgolfHQ home page. Prefers an explicit liveStatus flag
// (manually set), then falls back to today's date against startDate/endDate
// so the widget stays current without anyone having to flip a flag. If two+
// events share the same next startDate (e.g. a shared opening weekend), all
// of them are returned so a card renders for each.
export function listLiveSeniorTournaments(): SeniorMajorEvent[] {
  const explicitLive = SENIOR_MAJOR_EVENTS_2026.filter((t) => t.liveStatus === "live");
  if (explicitLive.length > 0) return explicitLive;

  const today = new Date().toISOString().slice(0, 10);

  const dateLive = SENIOR_MAJOR_EVENTS_2026.filter(
    (t) => t.startDate && t.endDate && t.startDate <= today && today <= t.endDate
  );
  if (dateLive.length > 0) return dateLive.map((t) => ({ ...t, liveStatus: "live" as const }));

  const explicitNext = SENIOR_MAJOR_EVENTS_2026.filter((t) => t.liveStatus === "next");
  if (explicitNext.length > 0) return explicitNext;

  const upcoming = SENIOR_MAJOR_EVENTS_2026
    .filter((t) => t.startDate && t.startDate > today && t.liveStatus !== "completed")
    .sort((a, b) => a.startDate!.localeCompare(b.startDate!));
  if (upcoming.length === 0) return [];

  const earliestStart = upcoming[0].startDate;
  return upcoming
    .filter((t) => t.startDate === earliestStart)
    .map((t) => ({ ...t, liveStatus: "next" as const }));
}
